[tool.poetry]
name = "jcalapi"
version = "0.1.0"
description = "Local calendar caching and JSON API"
authors = ["Philipp Schmitt <philipp@schmitt.co>"]
license = "GPL-3"

[tool.poetry.dependencies]
python = "^3.9"
aioify = "^0.4.0"
asynccli = "^0.1.3"
atlassian-python-api = "^3.14.1"
diskcache = "^5.2.1"
environs = "^9.3.4"
fastapi = "^0.70.0"
fastapi-utils = "^0.2.1"
httpx = "^0.20.0"
icalendar = "^4.0.8"
loguru = "^0.5.3"
python-dateutil = "^2.8.2"
recurring-ical-events = "^0.2.0-beta.0"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
xdg = "^5.1.1"
exchangelib = {git = "https://github.com/ecederstrand/exchangelib.git"}

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.1"
ipython = "^7.28.0"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
